### ISSUE TITLE
Frontmatter conventions

### ISSUE THREAD

**Issue by lorenzode** [decidim/training#1]
@all

For some technical reasons like absence of special language specific characters like Spanish accents which could confuse the built system the frontmatter should be in English. Sorry if I put English as the lingua franca here :).

Example: 

`--- meta
title:  ¿Cómo ganan dinero los servicios que usas en internet?
uuid:
locale: es
source: Tactical Tech
category:  concienciación
tags:
  - Rastreo y perfilaje
  - Corredores de datos
  - GAFAM
  - Modelos de negocios
duration:  45
description:  ¿Cómo ganan dinero los servicios que usas en internet? Analizar cuales son los modelos de negocios de las grandes empresas que proveen servicios en internet (Google, Amazon, Facebook, Apple, Microsoft) permite entender sus motivaciones y practicas y como estas nos pueden afectar.
---`

Also pls note that we changed 'lan' to 'locale' and that the ISO 639-1 code for Spanish is 'es' (replaces 'sp') and for Catalan 'ca'.

Happy to discuss any conventions which you think don't fit your needs! :)

**Comment by alexandraTTC** [comment]
ah ok oups ... i will change it in all sessions thank you!

**Comment by lorenzode** [comment]
I changed it already in the files currently on master. Waiting for perms to push...
