### ISSUE TITLE
Fixing tags

### ISSUE THREAD

**Issue by lorenzode** [decidim/training#13]
The tagging/selection system is to overwhelming. There are too many
tags. So we probably need to do two things:
1. Reinstate the initial selection of awareness, capacity, methodology
and  argue for reference docs
2. Build on tags that appear in curricula PoD (myshadow.org/train)

who: Alex sends a list of tags suggestion and/or the current visualised
tags come from where? i can change the tags directly on the mk files but
unsure about which ones are being visualised right now, tags on the
metadata??

**Comment by lorenzode** [comment]
@alexandraTTC 

About your question: yes, tags from the meta are being picked up.

@killapop @Fieke

**Comment by killapop** [comment]
@alexandraTTC @lorenzode 

The tags come from the md files. they collect all of them from all the available files and display a unique list of them. Please take care of case sensitivity and spelling, spaces, underscores, hyphens etc.

for eg:
`in file a.md`
```
tags:
  - cats and dogs
  - cows and goats
```

`in file b.md`
```
tags:
  - cows and goats
  - Cats and dogs
````
would make a set of tags 
```
- cats and dogs
- Cats and dogs
- cows and goats
```

**Comment by alexandraTTC** [comment]
i fixed the tags last week, maybe people of decidim want to go for another tag system, up to them now
