### ISSUE TITLE
Link to Readme

### ISSUE THREAD

**Issue by lorenzode** [decidim/training#19]
The readme needs to be published in the UI, the one with the credits
etc. I was thinking either a link in the bottom right or on in the
banner. It can link to the Github readme

@killapop @Fiekej @alexandraTTC

**Comment by lorenzode** [comment]
@alexandraTTC Can you pls tell me the Spanish label for the link?

**Comment by alexandraTTC** [comment]
unsure about your question, what lbel?
the link is here:
https://github.com/decidim/training/blob/master/content/README

the readme in spanish would be:
presentación y créditos
